FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN set -e; \
    apt-get update ;\
    apt-get -y install netcat-traditional ;\
    apt-get -y install gettext ;\
    apt-get -y install httpie ;\
    python -m pip install --upgrade pip ;\
    pip install flask

RUN mkdir /code
WORKDIR /code
COPY ./server.py .

EXPOSE 5000

ENTRYPOINT ["python", "./server.py"]
